---
- name: Restore playbook.yml
  hosts: all
  vars:
    svc_db: mairadb
  tasks: 
    # /etc/motd (size = 0 )파일 비우기
    # DB 서비스 비활성화
    # DB 패키지 삭제
    - name: /etc/motd 파일 복원
      shell: "> /etc/motd"

    - name: DB 서비스 종료
      service:
        name: mariadb
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: DB 패키지 삭제
      yum:
        name:
          - python3-PyMySQL
          - mariadb-server
        state: absent
    
