---
- name: Restore playbook.yml
  hosts: all
  tasks:
    # 1) /etc/ansible/facts.d 디렉토리 삭제 (file)
    # 2) 웹 서비스 종료 - httpd (service)
    # 3) 웹 패키지 삭제 - httpd (yum)
    - name: 1) /etc/ansible/facts.d 디렉토리 삭제 (file)
      file:
        path: /etc/ansible/facts.d
        state: absent
    
    - name: 2) 웹 서비스 종료 - httpd (service)
      service:
        name: httpd
        state: stopped
      
    - name: 3) 웹 패키지 삭제 - httpd (yum)
      yum:
        name: httpd
        state: absent