---
- name: fileserver 패키지 설치
  hosts: fileservers
  tasks:
    - name: 변수 포함
      ansible.builtin.include_vars: package.yml

    - name: 테스크 포함
      ansible.builtin.include_tasks: install_package.yml
      
        
        