---
- name: Install ans start apache httpd
  hosts: webservers
  tasks: 
    # 1) 패키지 설치(yum -y install httpd mod_ssl)
    # 2) 서비스 설정(cp files/index.html target:/var/www/html/index.html)
    # 3) 서비스 기동(systemctl enable --now httpd)
    # 4) 방화벽 등록(firewall-cmd --permanent --add-service={http,https})
    # 5) SELinux(?)

    # 1) 패키지 설치(yum -y install httpd mod_ssl)
    - name: 1) Install the package - httpd, mod_ssl
      yum:
        name:
          - httpd
          - mod_ssl
        state: present

    # 2) 서비스 설정(cp files/index.html target:/var/www/html/index.html)
    - name: 2) Configuration the web service with httpd
      copy: 
        src: files/index.html
        dest: /var/www/html/index.html

    # 3) 서비스 기동(systemctl enable --now httpd)
    - name: 3) Start the web service
      service:
        name: httpd
        state: started
        enabled: yes

    # 4) 방화벽 등록(firewall-cmd --permanent --add-service={http,https})
    - name: 4) Configure the firewalld
      firewalld: 
        service: "{{ item }}" # 한번에 두개를 지정할 수 없음 , 반복 구문으로 처리 , "{{ item }}" << loop 밑 인자들 입력됨 , 변수 이름 하나로 여려번의 작업 가능
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https