---
- name: 웹 서버 설정 및 확인(인증)
  hosts: ansible1.example.com
  vars:
    pkg_fw: firewalld
    pkg_http: httpd
    pkg_https: https
    conf_httpd_src: files/httpd.conf
    conf_httpd_dest: /etc/httpd/conf/httpd.conf
    htaccess_src: files/.htaccessw
    htaccess_dest: "{{ web_root }}/.htaccess"
    secrets_dir: /etc/httpd/secrets
    secrets_src: files/htpasswd
    secrets_dest: "{{ secrets_dir }}/htpasswd"
    web_root: /var/www/html
    svc_fw: firewalld
    svc_web: httpd
    fw_http: http
    fw_https: https
    
  tasks:
    # 1) 패키지 설치 - firewwalld, httpd, mod_ssl
    # 2) 웹 서비스 설정
    # 2-1) /etc/httpd/conf/httpd.conf (files/httpd.conf)
    # 2-2) /var/www/html/.htaccess (files/.htaccess)
    # 2-3) /etc/httpd/secrets/htpasswd (files/htpasswd)
    # * /etc/httpd/secrets 디렉토리 생성
    # * /etc/httpd/secrets/htpasswd 파일 배포
    # 2-4) /var/www/html/index.html (using the facts)
    # * ansible1.example.com - ip
    # 3) 서비스 기동 - firewalld, httpd
    # 4) 방화벽 서비스 등록 - http, https
    # 5) 테스트 - 인증

    # 1) 패키지 설치 - firewalld, httpd, mod_ssl
    - name: 1) 패키지 설치 - firewalld, httpd, mod_ssl
      yum: 
        name:
          - "{{ pkg_fw }}"
          - "{{ pkg_http }}"
          - "{{ pkg_https }}"
        state: present
    # 2) 웹 서비스 설정
    # 2-1) /etc/httpd/conf/httpd.conf (files/httpd.conf)
    - name: 2-1) /etc/httpd/conf/httpd.conf (files/httpd.conf)

    # 2-2) /var/www/html/.htaccess (files/.htaccess)
    # 2-3) /etc/httpd/secrets/htpasswd (files/htpasswd)
    # * /etc/httpd/secrets 디렉토리 생성
    # * /etc/httpd/secrets/htpasswd 파일 배포
    - name: 2-3-2) 
      copy:
        src: "{{ secrets_src }}"
        dest: "{{ secrets_dest }}"
        owner: apache
        group: apache
        mode: '0400'

    # 2-4) /var/www/html/index.html (using the facts)
    # * ansible1.example.com - ip
    - name: 2-4)
      ansible.builtin.copy:
        content: "Hostname: {{ ansible_hostname }} - IPv4: {{ ansible }}"
        dest: "{{ web_root }}/index.html"

    # 3) 서비스 기동 - firewalld, httpd
    - name: 3) 서비스 기동 - firewalld, httpd
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - "{{ fw_http }}"
        - "{{ fw_https }}"

    # 4) 방화벽 서비스 등록 - http, https
      firewalld:
        name:
    # 5) 테스트 - 인증_
- name:
  hosts: localhost
  vars:
    url: ansible1.example.com
    request_url1: "http://{{ url }}"
    request_url2: "https://{{ url }}"
    web_user: guest
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: Test Web Service
      uri:
        url: "{{ request_url1 }}"
        user: "{{ web_user }}"
        password: 
        validate_certs: false
        force_basic_auth: yes
        status_code: 200