# 사용자 제거
---
- name: 추가된 사용자 제거
  hosts: devservers
  remote_user: devops
  become: true
  vars_files:
    - vars/secret.yml
  tasks:
    - name: 사용자 제거
      user:
        name: "{{ item.name }}"
        state: absent
        remove: yes
      with_items: "{{ newusers }}"