- name: Restore playbook
  hosts: webserver
  vars_files: vars/vars.yml
  tasks:
    # 4) 패키지 삭제 - httpd, mod_ssl, python3-PyMySQL, firewalld
    # 3) 서비스 설정 - /var/www/html/index.html
    # 2) 서비스 정지 - firewalld, httpd
    # 1) 방화벽 삭제 - http, https

    # 1) 방화벽 삭제 - http, https
    - name: 방화벽 따운 - {{ fw_http }}, {{ fw_https }}
      firewalld:
        service: "{{ item }}"
        permanent: no
        state: disabled
      loop:
        - "{{ fw_http }}"
        - "{{ fw_https }}"
      ignore_errors: yes

    # 2) 서비스 정지 - firewalld, httpd
    - name: 서비스 정지 - {{ svc_fw }}, {{ svc_web }}
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - "{{ svc_fw }}"
        - "{{ svc_web }}"
      ignore_errors: yes
    # 3) 서비스 설정 - /var/www/html/index.html
    - name: 서비스 삭제 - /var/www/html/index.html
      file:
        path: /var/www/html/index.html
        state: absent

    # 4) 패키지 삭제 - httpd, mod_ssl, python3-PyMySQL, firewalld
    - name: 패키지 삭제 - {{ pkg_http }}, {{ pkg_https }}, {{ pkg_python }}, {{ pgk_fw }}
      yum:
        name:
          - "{{ pkg_http }}"
          - "{{ pkg_https }}"
          - "{{ pkg_python }}"
          - "{{ pgk_fw }}"
        state: absent

