---
- name: Restore playbook.yml
  hosts: all
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
    mariadb_service: mariadb
  tasks:
    # 1) 서비스 비활성화
    # 2) 패키지 삭제
    - name: 서비스 비활성화
      service:
        name: "{{ mariadb_service }}"
        state: stopped
    
    - name: 패키지 삭제
      yum:
        name: "{{ item }}"
        state: absent
      with_items: "{{ mariadb_packages }}"
      

