---
- name: Tasks 
  hosts: databases
  gather_facts: no
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Check Local Time
      command: date
      register: command_result
      changed_when: false

    - name: Print Local time
      debug:
        var: command_result.stdout

    - name: blocak ~~
      block:
      - name: 패키지 설치
        yum:
          name: "{{ web_package }}"
          state: present
        failed_when: web_package == "httpd"
      rescue:
      - name: 설치 패키지
        yum:
          name: "{{ db_package }}"
          state: present
      always:
      - name: 서비스 기동
        service:
          name: "{{ db_service }}"
          state: started
          enabled: yes

    